services:
  postgres:
    image: postgres:15-alpine
    container_name: mixology_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mixology_hub
    ports:
      - "5433:5432"  # <-- El host usará 5433, el contenedor internamente sigue en 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mixology_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
